langage: php
php:
  - '7.4'

sudo: false
cache:
  directoryes:
    - $HOME/var/cache

env:
    global:
      - PHPUNIT_FLAGS="-v"
      - SYMFONY_PHPUNIT_DIR-"$HOME/symfony-bridge/.phpunit"

matrix:
  fast_finish: true
  allow_failures:
    - env: STABILITY="dev"

before_install:
  - if [[$COVERAGE != true ]]; then phpenv config-rm xdebug.ini || true; fi


install:
  - composer update ${COMPOSER_FLAGS} --prefer-dist --no-interacion
  - ./vendor/bin/simple-phpunit install

script:
  - composer validate --strict --no-check-lock
  - ./vendor/bin/simple-phpunit $PHPUNIT_FLAGS